# Generated by Django 2.2.26 on 2022-06-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='Body',
        ),
    ]
